### ISSUE TITLE
Why not just use the uuid library?

### ISSUE THREAD

**Issue by x94carbone** [AI-multimodal/aimmdb#17]
Referring to the [uid module](https://github.com/AI-multimodal/aimmdb/blob/673b5ce88ef21ec259c5a262712e58ad9c31e2a6/aimmdb/uid.py). Just curious since by default that's my go-to.

**Comment by kleinhenz** [comment]
Since we use the uids as user visible keys it seems valuable to keep them reasonably short so that they are easier to recognize/type/copy.

**Comment by x94carbone** [comment]
I see. Any reason you're not using a library for it e.g. [shortuuid](https://pypi.org/project/shortuuid/)? I'm just wondering, it's not a big deal. We'll use whatever you decide on for adding new uids to the post-processed data to ensure consistency.

**Comment by kleinhenz** [comment]
yes, as I mention in the code shortuuid is the origin of the idea. It's not a very long or complicated piece of code so I don't see much point in bringing in a dependency.
