### ISSUE TITLE
API key usage should bypass requirement of client.login()

### ISSUE THREAD

**Issue by x94carbone** [AI-multimodal/aimmdb#18]
@kleinhenz It would be really nice to not have to run e.g.

```python
client = from_uri("https://aimm.lbl.gov/api")
client.login()  # <--- this
```

in order to access the private databases when my API key is already set. Any way to do this? Or is this a tiled issue not an aimmdb one?

**Comment by kleinhenz** [comment]
yeah this an annoying consequence of having some of the data public. The issue is with tiled. Do you mind opening an issue there?
