### ISSUE TITLE
Confirm that hard XAS data from APS has been ingested

### ISSUE THREAD

**Issue by danielballan** [AI-multimodal/aimmdb#30]
This is item 5b from the Google doc. Data owner is Inhui.

Data comprises Ni, Co and Mn (Inhui has both xanes and exafs).

**Comment by jmaruland** [comment]
I had a meeting with Inhui and we went through the nmc data from APS. I showed him that if we filter by dataset (nmc) and by facility name (APS), we get 107 entries (or files that were uploaded to aimmdb). I asked him if there were more files that they were planning to share/upload to ammdb and he said that those are all the nmc files he has.

**Comment by jmaruland** [comment]
How to find all the APS data in aimmdb:
```
In [36]: c['dataset']['nmc']['uid'].search(Key("facility.name") == "APS")
Out[36]: <AIMMCatalog {BM_NCM622 Ni-K (WwFMvg92n23), ...} ~107 entries>
```
where `c` is the tiled-client object
